[env]
platform = espressif32
framework = arduino
board = esp32dev
upload_speed = 921600
monitor_speed = 115200
lib_deps = 
	nrf24/RF24@^1.4.5

[env:esp32_ground]
build_flags = 
	-DGROUND_NODE
description = Ground station ESP32 (USB to Mission Planner)

[env:esp32_air]
build_flags = 
	-DAIR_NODE
description = Air-side ESP32 (connected to flight controller)
